insert into iam_region (region_code, region_name, parent_region_code, enabled, created_at)
select 'shaoxing-keqiao', '绍兴市柯桥区', 'city', true, current_timestamp
where not exists (select 1 from iam_region where region_code = 'shaoxing-keqiao');

insert into iam_user (id, display_name, role_code, region_code, enabled, created_at)
select 'keqiao-officer', '柯桥区一线人员', 'OFFICER', 'shaoxing-keqiao', true, current_timestamp
where not exists (select 1 from iam_user where id = 'keqiao-officer');

insert into iam_user (id, display_name, role_code, region_code, enabled, created_at)
select 'keqiao-manager', '柯桥区管理人员', 'MANAGER', 'shaoxing-keqiao', true, current_timestamp
where not exists (select 1 from iam_user where id = 'keqiao-manager');

create table if not exists fact_oil_fume_warning (
    id bigint generated by default as identity primary key,
    warning_date date not null,
    street_name varchar(120) not null,
    region_code varchar(64) not null,
    warning_level varchar(32) not null,
    warning_count integer not null,
    unclosed_count integer not null,
    avg_concentration decimal(10, 2) not null,
    max_concentration decimal(10, 2) not null
);
