create table if not exists oil_fume_threshold_config (
    id bigint generated by default as identity primary key,
    region_code varchar(64) not null,
    standard_code varchar(64) not null,
    standard_name varchar(255) not null,
    max_allowed_concentration decimal(10, 2) not null,
    removal_efficiency_small integer not null,
    removal_efficiency_medium integer not null,
    removal_efficiency_large integer not null,
    source_url varchar(500),
    effective_from date not null,
    effective_to date,
    enabled boolean not null default true
);

create index if not exists idx_oil_fume_threshold_region_enabled
    on oil_fume_threshold_config(region_code, enabled, effective_from);
