create table if not exists dim_catering_unit (
    id bigint generated by default as identity primary key,
    unit_code varchar(64) not null,
    unit_name varchar(255) not null,
    street_name varchar(120) not null,
    region_code varchar(64) not null,
    business_type varchar(120),
    contact_name varchar(64),
    contact_phone varchar(32),
    purifier_model varchar(120),
    purifier_enabled boolean not null default true,
    online_status varchar(32) not null
);

create unique index if not exists uk_catering_unit_code
    on dim_catering_unit(unit_code);

create table if not exists fact_oil_fume_warning_event (
    id bigint generated by default as identity primary key,
    warning_batch_code varchar(64) not null,
    unit_code varchar(64) not null,
    street_name varchar(120) not null,
    region_code varchar(64) not null,
    warning_date date not null,
    warning_level varchar(32) not null,
    warning_source varchar(64) not null,
    device_code varchar(64) not null,
    warning_count integer not null,
    unclosed_count integer not null,
    avg_concentration decimal(10, 2) not null,
    max_concentration decimal(10, 2) not null,
    latest_status varchar(32) not null
);

create unique index if not exists uk_oil_fume_warning_batch_code
    on fact_oil_fume_warning_event(warning_batch_code);

create index if not exists idx_oil_fume_warning_event_region_date
    on fact_oil_fume_warning_event(region_code, warning_date);

create table if not exists fact_oil_fume_closure_record (
    id bigint generated by default as identity primary key,
    warning_batch_code varchar(64) not null,
    closed_count integer not null,
    closure_status varchar(32) not null,
    disposed_at timestamp,
    disposed_by varchar(64),
    disposal_measure varchar(255),
    result_summary varchar(500)
);

create index if not exists idx_oil_fume_closure_record_batch
    on fact_oil_fume_closure_record(warning_batch_code);

create table if not exists fact_oil_fume_device_inspection (
    id bigint generated by default as identity primary key,
    unit_code varchar(64) not null,
    inspection_date date not null,
    street_name varchar(120) not null,
    region_code varchar(64) not null,
    inspector_name varchar(64) not null,
    purifier_running boolean not null,
    purifier_cleaned boolean not null,
    online_status varchar(32) not null,
    issue_found boolean not null,
    issue_note varchar(500)
);

create index if not exists idx_oil_fume_device_inspection_region_date
    on fact_oil_fume_device_inspection(region_code, inspection_date);
